"""Add access logs

Revision ID: 0e3cb86073ba
Revises: bae18bf91a5e
Create Date: 2026-07-17 16:07:42.903390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3cb86073ba'
down_revision: Union[str, Sequence[str], None] = 'bae18bf91a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('ENTRY', 'EXIT', name='accessdirectionenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('plate_scan_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['plate_scan_id'], ['plate_scans.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_logs')
    # ### end Alembic commands ###
