"""add_webhook_url_to_dispositivo

Revision ID: 3aa735770818
Revises: 9d8f2a1c4b77
Create Date: 2026-07-26 23:03:37.915808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa735770818'
down_revision: Union[str, Sequence[str], None] = '9d8f2a1c4b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_accesos_imagen_id_archivos_multimedia'), 'accesos', type_='foreignkey')
    op.create_foreign_key(None, 'accesos', 'archivos_multimedia', ['imagen_id'], ['id'])
    op.add_column('dispositivos', sa.Column('webhook_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('fk_usuarios_foto_id_archivos_multimedia'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'archivos_multimedia', ['foto_id'], ['id'])
    op.drop_constraint(op.f('fk_vehiculos_foto_id_archivos_multimedia'), 'vehiculos', type_='foreignkey')
    op.create_foreign_key(None, 'vehiculos', 'archivos_multimedia', ['foto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehiculos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vehiculos_foto_id_archivos_multimedia'), 'vehiculos', 'archivos_multimedia', ['foto_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios_foto_id_archivos_multimedia'), 'usuarios', 'archivos_multimedia', ['foto_id'], ['id'], ondelete='SET NULL')
    op.drop_column('dispositivos', 'webhook_url')
    op.drop_constraint(None, 'accesos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_accesos_imagen_id_archivos_multimedia'), 'accesos', 'archivos_multimedia', ['imagen_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
