"""unique_document_id

Revision ID: 58773c46f6cd
Revises: 0e3cb86073ba
Create Date: 2026-07-17 17:34:25.014545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58773c46f6cd'
down_revision: Union[str, Sequence[str], None] = '0e3cb86073ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_university_persons_document_id'), 'university_persons', ['document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_university_persons_document_id'), table_name='university_persons')
    # ### end Alembic commands ###
