"""initial_enterprise_schema

Revision ID: 6784f2a204a1
Revises: 
Create Date: 2026-07-20 13:54:02.526457

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6784f2a204a1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_dispositivo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_vehiculo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido_paterno', sa.String(), nullable=False),
    sa.Column('apellido_materno', sa.String(), nullable=True),
    sa.Column('carnet', sa.String(), nullable=False),
    sa.Column('contrasena_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('ADMINISTRADOR', 'OPERADOR', 'DISPOSITIVO', 'USUARIO', name='roleenum'), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.Column('actualizado_el', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_carnet'), 'usuarios', ['carnet'], unique=True)
    op.create_table('dispositivos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.Column('tipo_dispositivo_id', sa.Uuid(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.Column('actualizado_el', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_dispositivo_id'], ['tipos_dispositivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('marca_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('propietario_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.Column('actualizado_el', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['propietario_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipos_vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('escaneados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ruta_imagen', sa.String(), nullable=True),
    sa.Column('placa_detectada', sa.String(), nullable=True),
    sa.Column('placa_normalizada', sa.String(), nullable=True),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('DETECTADO', 'BAJA_CONFIANZA', 'ERROR', 'MANUAL', name='estadoescaneoenum'), nullable=False),
    sa.Column('dispositivo_id', sa.Uuid(), nullable=True),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=True),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escaneados_creado_el'), 'escaneados', ['creado_el'], unique=False)
    op.create_index(op.f('ix_escaneados_placa_normalizada'), 'escaneados', ['placa_normalizada'], unique=False)
    op.create_table('accesos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_acceso', sa.Enum('ENTRADA', 'SALIDA', name='tipoaccesoenum'), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.Column('escaneado_id', sa.Uuid(), nullable=False),
    sa.Column('operador_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('creado_el', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escaneado_id'], ['escaneados.id'], ),
    sa.ForeignKeyConstraint(['operador_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesos_creado_el'), 'accesos', ['creado_el'], unique=False)
    op.create_table('accesos_visitantes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_conductor', sa.String(), nullable=False),
    sa.Column('carnet_conductor', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('institucion_empresa', sa.String(), nullable=True),
    sa.Column('escaneado_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['escaneado_id'], ['escaneados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesos_visitantes_carnet_conductor'), 'accesos_visitantes', ['carnet_conductor'], unique=False)
    op.create_table('estado_campus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('DENTRO', 'FUERA', name='ubicacionvehiculoenum'), nullable=False),
    sa.Column('ultimo_acceso_id', sa.Uuid(), nullable=False),
    sa.Column('actualizado_el', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ultimo_acceso_id'], ['accesos.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehiculo_id')
    )
    op.create_index(op.f('ix_estado_campus_actualizado_el'), 'estado_campus', ['actualizado_el'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estado_campus_actualizado_el'), table_name='estado_campus')
    op.drop_table('estado_campus')
    op.drop_index(op.f('ix_accesos_visitantes_carnet_conductor'), table_name='accesos_visitantes')
    op.drop_table('accesos_visitantes')
    op.drop_index(op.f('ix_accesos_creado_el'), table_name='accesos')
    op.drop_table('accesos')
    op.drop_index(op.f('ix_escaneados_placa_normalizada'), table_name='escaneados')
    op.drop_index(op.f('ix_escaneados_creado_el'), table_name='escaneados')
    op.drop_table('escaneados')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('dispositivos')
    op.drop_index(op.f('ix_usuarios_carnet'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_vehiculo')
    op.drop_table('tipos_dispositivo')
    op.drop_table('marcas')
    # ### end Alembic commands ###
